services:
  cryptoupdate_cli:
    container_name: cryptoupdate_cli
    build:
      context: .
      dockerfile: Dockerfile.cli
    volumes:
      - ./archives:/home/docker/app/archives
      - ./data:/home/docker/app/data

    