services:
  cryptoupdate:
    container_name: cryptoupdate
    build:
      context: .
    image: chrysalide/cryptoupdate:1.2.0
    develop:
      watch:
        - action: sync
          path: .
          target: /home/docker/app/
    ports:
      - "8080:8080"
    volumes:
      - ./archives:/home/docker/app/archives
      - ./data:/home/docker/app/data
    restart: unless-stopped

  cryptoupdate_cli:
    container_name: cryptoupdate_cli
    build:
      context: .
      dockerfile: Dockerfile.cli
    image: chrysalide/cryptoupdate_cli:1.2.0
    profiles:
      - cli
    volumes:
      - ./archives:/home/docker/app/archives
      - ./data:/home/docker/app/data
    