services:
  cryptoupdate:
    container_name: cryptoupdate
    build:
      context: .
    develop:
      watch:
        - action: sync
          path: .
          target: /home/docker/app/
    ports:
      - "8042:8080"
    volumes:
      - ./archives:/home/docker/app/archives
      - ./data:/home/docker/app/data
    restart: unless-stopped
    