version: '3.8'

services:
  cryptoupdate:
    image: cryptoupdate
    volumes:
      - ./data/inputs:/home/docker/inputs
      - ./data/outputs:/home/docker/outputs
      - ./data/archives:/home/docker/archives

