version: '3.8'

services:
  cryptoupdate:
    build: .
    user: "1000:1000"
    volumes:
      - ./data/inputs:/home/docker/inputs
      - ./data/outputs:/home/docker/outputs
      - ./data/archives:/home/docker/archives
