# Generated by Django 5.0.7 on 2024-08-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100)),
                ('amount_invested', models.FloatField()),
                ('coins_invested', models.FloatField()),
                ('coin_price', models.FloatField()),
                ('coins_count', models.FloatField()),
                ('wallet_value', models.FloatField()),
                ('nfts_count', models.FloatField()),
                ('nfts_value', models.FloatField()),
                ('total_value', models.FloatField()),
                ('profit', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
