# Generated by Django 5.1.1 on 2024-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvstore',
            name='amount_invested',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='coin_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='coins_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='coins_invested',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='nfts_count',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='nfts_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='profit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='total_value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='csvstore',
            name='wallet_value',
            field=models.FloatField(default=0),
        ),
    ]
