# Generated by Django 5.1.1 on 2024-09-13 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvstore', '0003_csvstore_timestamp_add_alter_csvstore_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csvstore',
            name='timestamp_add',
        ),
    ]
