# Generated by Django 5.1.1 on 2024-09-13 20:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvstore', '0004_remove_csvstore_timestamp_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvstore',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
