# Generated by Django 5.1.1 on 2024-09-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvstore', '0005_alter_csvstore_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvstore',
            name='timestamp',
            field=models.IntegerField(default=0),
        ),
    ]
