version: '3.8'

services:
  mcp-sqlite-server:
    build:
      context: .
      dockerfile: Dockerfile.mcp
    container_name: crypto-mcp-sqlite
    ports:
      - "3000:3000"
    volumes:
      # Mount SQLite database for persistence
      - ./data:/app/data
      # Optional: Mount logs directory
      - ./logs:/app/logs
    environment:
      - MCP_SQLITE_DB_PATH=/app/data/db.sqlite3
      - PYTHONPATH=/app
      # Optional: Set log level
      - LOG_LEVEL=INFO
    restart: unless-stopped
    networks:
      - mcp-network
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.1'

  # Optional: SQLite browser for database management
  sqlite-browser:
    image: linuxserver/sqlitebrowser:latest
    container_name: crypto-sqlite-browser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3000"
    restart: unless-stopped
    networks:
      - mcp-network
    depends_on:
      - mcp-sqlite-server

networks:
  mcp-network:
    driver: bridge

volumes:
  sqlite-data:
    driver: local